### ISSUE TITLE
User can select shapefiles from magicbox

### ISSUE THREAD

**Issue by mikefab** [unicef/magicbox-kepler-app#12]
#### What types of data?
- Shapefiles
  - We have GADM shapefiles for each country and at each admin level in Azure blob storage here:
    - Topojson [instructions](https://gist.github.com/mikefab/52f52c74935eb828f139991ed345a12c)

 
#### Where is the data stored
UNICEF uses Azure, so many static files are in Azure blob or file storage. [Here](https://github.com/Azure/azure-storage-node)  is an npm module to interact with Azure.
![screen shot 2018-10-12 at 8 46 50 pm](https://user-images.githubusercontent.com/42814/46899343-3e2b2f80-ce60-11e8-8888-cd30f598630c.png)

**Comment by thoat** [comment]
WIP on branch [azure-blobs-shapefile](https://github.com/unicef/magicbox-kepler-demo/compare/azure-blobs-shapefile). What's currently there include the logic of fetching blob lists and blobs, and mechanism for selecting country codes and admin levels. @marcellamaki will be integrating that with the AddData custom component.

**Comment by mikefab** [comment]
![screen shot 2018-12-26 at 11 59 41 am](https://user-images.githubusercontent.com/42814/50452042-ce2c3180-0905-11e9-88e9-9ed876f29877.png)
Completed by @marcellamaki and @thoat
