### ISSUE TITLE
Add auth to project

### ISSUE THREAD

**Issue by mikefab** [unicef/magicbox-kepler-app#8]
## What
Clone https://github.com/unicef/magicbox-aad-app as new projectlet in root.

## Context
Right now, our app does not have an authorization layer yet. The authorization protocol we desire lives in a separate project (listed above). What we want is to integrate this auth service into our demo app, which, we think, will smooth out our deployment process. 

We see two potential ways to integrate auth: 

1. Add the auth functionality directly to the demo application code
2. Use containers/docker compose to run as two separate but connected projects, on different ports, and operate as microservices, with Kepler possibly beamed in through an iframe on the page where the user gets redirected to on login.

## Outcome
The ideal outcome would be to have a functioning, deployed version of the app (in its current iteration) with an auth layer. If you have an alternate suggestion for how this could be done, we are open to creative solutions different than the suggestions above that include a write up and code demo.

**Comment by bnwhorton** [comment]
So the big part of the auth would be the data that kepler loads and not the ui code kepler runs in right (github and all)? So really we providing the whole ui in the bundle.js and letting the users grab some from of token to pass to a api that can check it would be how id look at implementation. Would we be looking at keeping it in Azure or is there another auth platform youd look at/want?

**Comment by mikefab** [comment]
For auth, am thinking to run docker-compose with
- aquibm/react-azure-ad-demo 8080:3000
- unicef/magicbox-kepler-demo 5000

Where only 8080 is exposed, and the kepler demo is broadcast through an iframe after the user has logged in.

In this scenario, the kepler instance is only accessible after the user has logged in. 

From there, was thinking of having the browser communicate directory with Azure services for saving maps (config.json) in blob or file storage, and fetching datasets.

**Comment by mikefab** [comment]
Done with https://github.com/unicef/magicbox-msal-graph-service/issues/1
